import os
from typing import List, Dict, Any, Optional

# Strip proxy environment variables for the current Python process
for env_var in ["HTTP_PROXY", "HTTPS_PROXY", "http_proxy", "https_proxy", "ALL_PROXY", "all_proxy"]:
    os.environ.pop(env_var, None)

from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from langgraph.prebuilt import create_react_agent

from core.config import settings
from services.agent.tools import AGENT_TOOLS

SYSTEM_PROMPT = """You are Aegis, an AI lore analyst and knowledge assistant specialized in Warhammer 40K and technical domain knowledge.

Your strict operational rules:
1. If the user query requires factual lore, Primarch details, or domain specifics, ALWAYS invoke `search_knowledge_base`.
2. Base your final response strictly on the retrieved context when present. Cite sources where possible.
3. If no relevant context is found in the database, explicitly state that before giving a general response.
"""

class AegisAgent:
    def __init__(self):
        model_name = getattr(settings, "LLM_MODEL", "llama3.2:3b")

        # Local Ollama client setup
        self.llm = ChatOllama(
            model=model_name,
            base_url="http://127.0.0.1:11434",
            temperature=0.2,
        )
        self.tools = AGENT_TOOLS

        self.agent_executor = create_react_agent(
            model=self.llm,
            tools=self.tools,
            prompt=SYSTEM_PROMPT,
        )

    async def run(
        self,
        query: str,
        history: Optional[List[Dict[str, str]]] = None
    ) -> Dict[str, Any]:
        messages = []
        if history:
            for msg in history:
                if msg.get("role") == "user":
                    messages.append(HumanMessage(content=msg.get("content", "")))
                elif msg.get("role") == "assistant":
                    messages.append(AIMessage(content=msg.get("content", "")))

        messages.append(HumanMessage(content=query))

        try:
            response = await self.agent_executor.ainvoke({"messages": messages})
            final_messages = response.get("messages", [])

            retrieved_contexts = []
            answer_text = ""

            for msg in final_messages:
                # Collect tool execution results for RAG evaluation
                if isinstance(msg, ToolMessage):
                    retrieved_contexts.append(str(msg.content))
                elif isinstance(msg, AIMessage) and msg.content:
                    answer_text = str(msg.content)

            if not answer_text and final_messages:
                answer_text = str(final_messages[-1].content)

            return {
                "output": answer_text or "No output generated by agent.",
                "retrieved_contexts": retrieved_contexts
            }
        except Exception as e:
            return {
                "output": f"[Agent Local Execution Error] {str(e)}",
                "retrieved_contexts": []
            }